#!/bin/bash

# Helper script to test API endpoints with authentication
# This script helps you extract cookies and test endpoints

BASE_URL="${BASE_URL:-http://localhost:3000}"

echo "=========================================="
echo "API Authentication Test Helper"
echo "=========================================="
echo ""
echo "This script helps you test API endpoints with authentication."
echo ""
echo "STEP 1: Get your authentication cookie"
echo "----------------------------------------"
echo "1. Open your browser and log in to: $BASE_URL"
echo "2. Open DevTools (F12 or Cmd+Option+I)"
echo "3. Go to: Application → Cookies → http://localhost:3000"
echo "4. Find the cookie named 'next-auth.session-token'"
echo "5. Copy its value"
echo ""
echo "STEP 2: Run the test"
echo "----------------------------------------"
echo "Run: COOKIES='next-auth.session-token=YOUR_TOKEN_VALUE' ./test-api-endpoints.sh"
echo ""
echo "Or test individual endpoints:"
echo ""
echo "# Get user profile:"
echo "curl -H 'Cookie: next-auth.session-token=YOUR_TOKEN' $BASE_URL/api/users/get"
echo ""
echo "# Get messages:"
echo "curl -H 'Cookie: next-auth.session-token=YOUR_TOKEN' $BASE_URL/api/messages/get"
echo ""
echo "# Save user profile:"
echo "curl -X POST -H 'Content-Type: application/json' -H 'Cookie: next-auth.session-token=YOUR_TOKEN' \\"
echo "  -d '{\"name\":\"Test User\",\"dateOfBirth\":\"1990-01-01\",\"languages\":[\"english\"]}' \\"
echo "  $BASE_URL/api/users/save"
echo ""
echo "# Save messages:"
echo "curl -X POST -H 'Content-Type: application/json' -H 'Cookie: next-auth.session-token=YOUR_TOKEN' \\"
echo "  -d '{\"messages\":[{\"id\":\"1\",\"role\":\"user\",\"content\":\"Hello\",\"timestamp\":1234567890}]}' \\"
echo "  $BASE_URL/api/messages/save"
echo ""
echo "=========================================="

